name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e '.[all]'
      - name: Lint with flake8
        run: |
          flake8 hawkesnest tests
      - name: Type-check with mypy
        run: |
          mypy hawkesnest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=hawkesnest
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
